### ISSUE TITLE
Promise chain

### ISSUE THREAD

**Issue by jmacwhyte** [san00/REST-countries-API#4]
https://github.com/san00/REST-countries-API/blob/1779cbe1bfd93280f3f8b4586318931f852ade73/src/js/main.js#L16

.then() is only used with promises. fetch() and response.json() both return promises, so they can make use of .then(). It is common to chain them together, but you could also break apart the chain and it would look like this:

```
// p1 will contain a promise returned from fetch
let p1 = fetch(url)

// p2 will contain a promise returned from response.json()
let p2 = p1.then(response => {
  return response.json();
})

// "data" is not a promise, so the value of "data" will be stored in "val"
let val = p2.then(data => {   
  return data
})
```

The rest of the functions in your chain don't return promises, so it doesn't make sense to call .then() on them.

This is your first hint ;) If you still can't figure it out, let me know and I will give you another one!

**Comment by san00** [comment]
Okay, thanks for this, I'll see how I get on :)

**Comment by san00** [comment]
Okay, I've given it a go, but I'd like another hint please.

**Comment by jmacwhyte** [comment]
@san00 

https://github.com/san00/REST-countries-API/blob/9f845fbe3f59aa8ecce9680e97448360bb799629/src/js/main.js#L10

`return countries` won't return a promise, so you don't need to catch it with .then(). Just do what you need to do right there, instead of `return`ing anything!

**Comment by san00** [comment]
Thanks for your help. 
I have a much better understanding of this now. 👍

**Comment by san00** [comment]
Thanks for your help.
I have a better understanding of this now. 👍
